### ISSUE TITLE
question about the results

### ISSUE THREAD

**Issue by Ixuanzhang** [lena-voita/the-story-of-heads#1]
I want to know the bleu result of the validation set shown in summary is the result of the network has only dev/sparsity_rate heads left?

**Comment by lena-voita** [comment]
Could you specify which result do you mean?

**Comment by Ixuanzhang** [comment]
![result](https://user-images.githubusercontent.com/8215764/86911683-4d7f0000-c14e-11ea-8930-cf61824b310e.png)
the result of bleu

**Comment by lena-voita** [comment]
1) The BLEU is evaluated in the testing regime, i.e. with some heads dropped. To check, you can take your checkpoint and look at which heads are pruned.

2) There's a notebook with heads visualization - you can easily use it to evaluate confidence.

Comment: your graphs look like you are training your model from scratch - do you? If you do, it's ok that BLEU doesn't drop: the model is training. Note that in the main experiments, we started pruning from already converged model.

**Comment by Ixuanzhang** [comment]
I understand.  
1、I did train from scratch. Next, I will try to start pruning from already converged model.
2、Regarding evaluate confidence, I will go to see how to use it.

Thank you very much!
